/* eslint-disable prettier/prettier */

import { TeamDto } from '../dto/team.dto';

export const teamData: TeamDto[] = [
  { id: 81, name: 'Barcelona', league: 'PD' },
  { id: 86, name: 'Real Madrid', league: 'PD' },
  { id: 65, name: 'Manchester City', league: 'PL' },
  { id: 57, name: 'Arsenal', league: 'PL' },
  { id: 64, name: 'Liverpool', league: 'PL' },
  { id: 5, name: 'Bayern Munich', league: 'BL1' },
  { id: 108, name: 'Inter Milan', league: 'SA' },
  { id: 524, name: 'PSG', league: 'FL1' },
];

export const allEuropeanLeaguesData: TeamDto[] = [
  // Premier League (PL)
  { id: 57, name: 'Arsenal FC', shortName: 'Arsenal', league: 'PL' },
  { id: 58, name: 'Aston Villa FC', shortName: 'Aston Villa', league: 'PL' },
  { id: 1044, name: 'AFC Bournemouth', shortName: 'Bournemouth', league: 'PL' },
  { id: 402, name: 'Brentford FC', shortName: 'Brentford', league: 'PL' },
  {
    id: 397,
    name: 'Brighton & Hove Albion FC',
    shortName: 'Brighton',
    league: 'PL',
  },
  { id: 61, name: 'Chelsea FC', shortName: 'Chelsea', league: 'PL' },
  {
    id: 354,
    name: 'Crystal Palace FC',
    shortName: 'Crystal Palace',
    league: 'PL',
  },
  { id: 62, name: 'Everton FC', shortName: 'Everton', league: 'PL' },
  { id: 63, name: 'Fulham FC', shortName: 'Fulham', league: 'PL' },
  { id: 349, name: 'Ipswich Town FC', shortName: 'Ipswich Town', league: 'PL' },
  { id: 338, name: 'Leicester City FC', shortName: 'Leicester', league: 'PL' },
  { id: 64, name: 'Liverpool FC', shortName: 'Liverpool', league: 'PL' },
  { id: 65, name: 'Manchester City FC', shortName: 'Man City', league: 'PL' },
  {
    id: 66,
    name: 'Manchester United FC',
    shortName: 'Man United',
    league: 'PL',
  },
  { id: 67, name: 'Newcastle United FC', shortName: 'Newcastle', league: 'PL' },
  {
    id: 351,
    name: 'Nottingham Forest FC',
    shortName: 'Nottingham',
    league: 'PL',
  },
  { id: 340, name: 'Southampton FC', shortName: 'Southampton', league: 'PL' },
  {
    id: 73,
    name: 'Tottenham Hotspur FC',
    shortName: 'Tottenham',
    league: 'PL',
  },
  { id: 563, name: 'West Ham United FC', shortName: 'West Ham', league: 'PL' },
  {
    id: 76,
    name: 'Wolverhampton Wanderers FC',
    shortName: 'Wolves',
    league: 'PL',
  },

  // La Liga (PD)
  { id: 77, name: 'Athletic Club', shortName: 'Athletic', league: 'PD' },
  { id: 78, name: 'Atlético de Madrid', shortName: 'Atlético', league: 'PD' },
  { id: 81, name: 'FC Barcelona', shortName: 'Barcelona', league: 'PD' },
  { id: 263, name: 'Deportivo Alavés', shortName: 'Alavés', league: 'PD' },
  { id: 558, name: 'RC Celta de Vigo', shortName: 'Celta Vigo', league: 'PD' },
  { id: 82, name: 'Getafe CF', shortName: 'Getafe', league: 'PD' },
  { id: 298, name: 'Girona FC', shortName: 'Girona', league: 'PD' },
  { id: 275, name: 'UD Las Palmas', shortName: 'Las Palmas', league: 'PD' },
  { id: 278, name: 'CD Leganés', shortName: 'Leganés', league: 'PD' },
  { id: 89, name: 'RCD Mallorca', shortName: 'Mallorca', league: 'PD' },
  { id: 79, name: 'CA Osasuna', shortName: 'Osasuna', league: 'PD' },
  { id: 87, name: 'Rayo Vallecano', shortName: 'Rayo Vallecano', league: 'PD' },
  {
    id: 90,
    name: 'Real Betis Balompié',
    shortName: 'Real Betis',
    league: 'PD',
  },
  { id: 86, name: 'Real Madrid CF', shortName: 'Real Madrid', league: 'PD' },
  {
    id: 92,
    name: 'Real Sociedad de Fútbol',
    shortName: 'Real Sociedad',
    league: 'PD',
  },
  { id: 559, name: 'Sevilla FC', shortName: 'Sevilla', league: 'PD' },
  { id: 94, name: 'Valencia CF', shortName: 'Valencia', league: 'PD' },
  {
    id: 267,
    name: 'Real Valladolid CF',
    shortName: 'Valladolid',
    league: 'PD',
  },
  { id: 95, name: 'Villarreal CF', shortName: 'Villarreal', league: 'PD' },
  {
    id: 280,
    name: 'RCD Espanyol de Barcelona',
    shortName: 'Espanyol',
    league: 'PD',
  },

  // Serie A (SA)
  { id: 102, name: 'Atalanta BC', shortName: 'Atalanta', league: 'SA' },
  { id: 103, name: 'Bologna FC 1909', shortName: 'Bologna', league: 'SA' },
  { id: 471, name: 'Cagliari Calcio', shortName: 'Cagliari', league: 'SA' },
  { id: 445, name: 'Como 1907', shortName: 'Como', league: 'SA' },
  { id: 470, name: 'Empoli FC', shortName: 'Empoli', league: 'SA' },
  { id: 99, name: 'ACF Fiorentina', shortName: 'Fiorentina', league: 'SA' },
  { id: 107, name: 'Genoa CFC', shortName: 'Genoa', league: 'SA' },
  {
    id: 108,
    name: 'FC Internazionale Milano',
    shortName: 'Inter',
    league: 'SA',
  },
  { id: 109, name: 'Juventus FC', shortName: 'Juventus', league: 'SA' },
  { id: 110, name: 'SS Lazio', shortName: 'Lazio', league: 'SA' },
  { id: 450, name: 'US Lecce', shortName: 'Lecce', league: 'SA' },
  { id: 98, name: 'AC Milan', shortName: 'Milan', league: 'SA' },
  { id: 472, name: 'AC Monza', shortName: 'Monza', league: 'SA' },
  { id: 113, name: 'SSC Napoli', shortName: 'Napoli', league: 'SA' },
  { id: 114, name: 'Parma Calcio 1913', shortName: 'Parma', league: 'SA' },
  { id: 100, name: 'AS Roma', shortName: 'Roma', league: 'SA' },
  { id: 115, name: 'Torino FC', shortName: 'Torino', league: 'SA' },
  { id: 112, name: 'Udinese Calcio', shortName: 'Udinese', league: 'SA' },
  {
    id: 455,
    name: 'Hellas Verona FC',
    shortName: 'Hellas Verona',
    league: 'SA',
  },
  { id: 584, name: 'Venezia FC', shortName: 'Venezia', league: 'SA' },

  // Bundesliga (BL1)
  { id: 16, name: 'FC Augsburg', shortName: 'Augsburg', league: 'BL1' },
  {
    id: 28,
    name: '1. FC Union Berlin',
    shortName: 'Union Berlin',
    league: 'BL1',
  },
  { id: 36, name: 'VfL Bochum 1848', shortName: 'Bochum', league: 'BL1' },
  {
    id: 12,
    name: 'SV Werder Bremen',
    shortName: 'Werder Bremen',
    league: 'BL1',
  },
  { id: 4, name: 'Borussia Dortmund', shortName: 'Dortmund', league: 'BL1' },
  {
    id: 19,
    name: 'Eintracht Frankfurt',
    shortName: 'Frankfurt',
    league: 'BL1',
  },
  { id: 17, name: 'SC Freiburg', shortName: 'Freiburg', league: 'BL1' },
  {
    id: 29,
    name: '1. FC Heidenheim 1846',
    shortName: 'Heidenheim',
    league: 'BL1',
  },
  {
    id: 18,
    name: 'TSG 1899 Hoffenheim',
    shortName: 'Hoffenheim',
    league: 'BL1',
  },
  { id: 45, name: 'Holstein Kiel', shortName: 'Holstein Kiel', league: 'BL1' },
  {
    id: 3,
    name: 'Bayer 04 Leverkusen',
    shortName: 'Leverkusen',
    league: 'BL1',
  },
  { id: 15, name: '1. FSV Mainz 05', shortName: 'Mainz', league: 'BL1' },
  {
    id: 2,
    name: 'Borussia Mönchengladbach',
    shortName: "M'gladbach",
    league: 'BL1',
  },
  { id: 5, name: 'FC Bayern München', shortName: 'Bayern', league: 'BL1' },
  { id: 721, name: 'RB Leipzig', shortName: 'RB Leipzig', league: 'BL1' },
  { id: 44, name: 'FC St. Pauli', shortName: 'St. Pauli', league: 'BL1' },
  { id: 10, name: 'VfB Stuttgart', shortName: 'Stuttgart', league: 'BL1' },
  { id: 11, name: 'VfL Wolfsburg', shortName: 'Wolfsburg', league: 'BL1' },

  // Ligue 1 (FL1)
  { id: 532, name: 'Angers SCO', shortName: 'Angers', league: 'FL1' },
  { id: 518, name: 'AJ Auxerre', shortName: 'Auxerre', league: 'FL1' },
  { id: 512, name: 'Stade Brestois 29', shortName: 'Brest', league: 'FL1' },
  { id: 531, name: 'Le Havre AC', shortName: 'Le Havre', league: 'FL1' },
  { id: 546, name: 'RC Lens', shortName: 'Lens', league: 'FL1' },
  { id: 521, name: 'Lille OSC', shortName: 'Lille', league: 'FL1' },
  { id: 523, name: 'Olympique Lyonnais', shortName: 'Lyon', league: 'FL1' },
  {
    id: 516,
    name: 'Olympique de Marseille',
    shortName: 'Marseille',
    league: 'FL1',
  },
  { id: 548, name: 'AS Monaco FC', shortName: 'Monaco', league: 'FL1' },
  { id: 511, name: 'Montpellier HSC', shortName: 'Montpellier', league: 'FL1' },
  { id: 526, name: 'FC Nantes', shortName: 'Nantes', league: 'FL1' },
  { id: 522, name: 'OGC Nice', shortName: 'Nice', league: 'FL1' },
  { id: 524, name: 'Paris Saint-Germain FC', shortName: 'PSG', league: 'FL1' },
  { id: 525, name: 'Stade de Reims', shortName: 'Reims', league: 'FL1' },
  {
    id: 529,
    name: 'Stade Rennais FC 1901',
    shortName: 'Rennes',
    league: 'FL1',
  },
  {
    id: 527,
    name: 'AS Saint-Étienne',
    shortName: 'Saint-Étienne',
    league: 'FL1',
  },
  {
    id: 576,
    name: 'RC Strasbourg Alsace',
    shortName: 'Strasbourg',
    league: 'FL1',
  },
  { id: 575, name: 'Toulouse FC', shortName: 'Toulouse', league: 'FL1' },
];
